language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - node

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: yarn cov && rm -rf ./coverage